name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    tags: 

jobs:
  create_release:
    name: Create Release
    runs-on: macOS-11
    steps:

      - uses: actions/checkout@v2

#       - name: Create XCFramework
#         uses: unsignedapps/swift-create-xcframework@v2
      
      - name: Install mint
        run: brew install mint
        
      - name: Install Create xcframework
        run: mint install unsignedapps/swift-create-xcframework
        
      - name: Install Create xcframework
        run: swift create-xcframework --stack-evolution
        
      - name: Upload release
        uses: yakuhzi/action-release@v1
        with:
          file: TypeFillKit.xcframework
          # changelog: /path/to/CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
