name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    tags: 

jobs:
  create_release:
    name: Create Release
    runs-on: macOS-11
    steps:

      - uses: actions/checkout@v2
      
      - name: Install mint
        run: brew install mint
        
      - name: Install Create xcframework
        run: mint install unsignedapps/swift-create-xcframework
        
      - name: Create xcframework
        run: /Users/runner/.mint/bin/swift-create-xcframework --stack-evolution

      - name: Upload release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release Build"
          files: |
            TypeFillKit.xcframework
