name: Swift

on: 
  push:
    branches: 
      - master
      - hotfix
    paths:
      - 'Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
  pull_request:
    paths:
      - 'Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'

concurrency: 
  group: ci
  cancel-in-progress: true

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12

    strategy:
      matrix:
        xcode: 
        - "14.1"

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Select ${{ matrix.xcode }}
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing Xcode_${{ matrix.xcode }}.app"
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version
        swift --version
        swift package --version

    - name: Get swift version
      run: swift --version # Swift 5.3.3

    - name: SPM Cache ${{ matrix.xcode }}
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-${{ matrix.xcode }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.xcode }}-spm-
      
    - name: Build ${{ matrix.xcode }}
      run: swift build -v
      
    - name: Run tests ${{ matrix.xcode }}
      run: swift test -v 2>&1 | xcpretty
